import './header/header.js'
import './home/home.js'
import './home/meals-list.js'
import './randomMeals/randomButton.js'
import './randomMeals/random_item.js'
import './randomMeals/random_list.js'
import './mealCategory/categoryList/category-item.js'
import './mealCategory/categoryList/category-list.js'